monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - ai_service # All logs from the AI service are logged in the "ai_service" channel

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!ai_service"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            # Dedicated AI service log
            ai_service:
                type: stream
                path: "%kernel.logs_dir%/aiservice.log"
                level: debug
                channels: ["ai_service"]
                formatter: monolog.formatter.ai_service

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!ai_service"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            # Dedicated AI service log (always log, even in prod)
            ai_service:
                type: stream
                path: "%kernel.logs_dir%/aiservice.log"
                level: info
                channels: ["ai_service"]
                formatter: monolog.formatter.ai_service


when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            # Dedicated AI service log (always log, even in prod)
            ai_service:
                type: stream
                path: "%kernel.logs_dir%/aiservice.log"
                level: info
                channels: ["ai_service"]
                formatter: monolog.formatter.ai_service
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
