<?php

namespace App\Controller\Admin;

use App\Entity\Photo;
use App\Entity\Tag;
use App\Repository\TagRepository;
use App\Service\AiImageAnalyzer;
use App\Service\ExifExtractor;
use App\Service\ImageResizer;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Filters;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator;
use Symfony\Component\HttpFoundation\RedirectResponse;

class PhotoCrudController extends AbstractCrudController
{
    public function __construct(
        private ExifExtractor $exifExtractor,
        private AiImageAnalyzer $aiImageAnalyzer,
        private TagRepository $tagRepository,
        private ImageResizer $imageResizer
    ) {
    }

    public static function getEntityFqcn(): string
    {
        return Photo::class;
    }

    public function configureActions(Actions $actions): Actions
    {
        $aiAnalyze = Action::new('aiAnalyze', 'AI Re-analyze', 'fa fa-robot')
            ->linkToCrudAction('analyzeWithAi')
            ->displayIf(static function (Photo $entity): bool {
                // Only show if photo has a filename
                return $entity->getFilename() !== null;
            })
            ->setCssClass('btn btn-info');

        return $actions
            ->add(Crud::PAGE_EDIT, $aiAnalyze);
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInSingular('Photo')
            ->setEntityLabelInPlural('Photos')
            ->setSearchFields(['name', 'description', 'location'])
            ->setDefaultSort(['uploadedAt' => 'DESC'])
            ->showEntityActionsInlined();
    }

    public function configureFilters(Filters $filters): Filters
    {
        return $filters
            ->add('albums')
            ->add('tags')
            ->add('user')
            ->add('viewPrivacy')
            ->add('createdAt')
            ->add('uploadedAt');
    }

    public function configureFields(string $pageName): iterable
    {
        $isNew = $pageName === Crud::PAGE_NEW;
        $isEdit = $pageName === Crud::PAGE_EDIT;

        yield IdField::new('id')
            ->hideOnForm();

        yield TextField::new('uuid')
            ->hideOnForm()
            ->formatValue(function ($value) {
                return $value ? $value->toRfc4122() : '';
            });

        // Show user on detail/index, but hide on forms (will be set automatically)
        yield AssociationField::new('user')
            ->hideOnForm();

        $nameField = TextField::new('name')
            ->setRequired(true);
        if ($isNew) {
            $nameField->setHelp('Will be auto-generated by AI, but you can change it');
        }
        yield $nameField;

        yield ImageField::new('filename')
            ->setBasePath('uploads/photos')
            ->setUploadDir('public/uploads/photos')
            ->setUploadedFileNamePattern('[randomhash].[extension]')
            ->setRequired($isNew)
            ->setLabel('Photo File');

        $descriptionField = TextareaField::new('description')
            ->hideOnIndex();
        if ($isNew) {
            $descriptionField->setHelp('Will be auto-generated by AI, but you can change it');
        }
        yield $descriptionField;

        yield ChoiceField::new('viewPrivacy')
            ->setChoices([
                'Public' => 'public',
                'Friends' => 'friend',
                'Family' => 'family',
                'Private' => 'private',
            ])
            ->setRequired(true);

        yield IntegerField::new('likeCount')
            ->hideOnForm();

        yield ChoiceField::new('rating')
            ->setChoices([
                '1 Star' => 1,
                '2 Stars' => 2,
                '3 Stars' => 3,
                '4 Stars' => 4,
                '5 Stars' => 5,
            ])
            ->renderAsBadges([
                1 => 'danger',
                2 => 'warning',
                3 => 'info',
                4 => 'primary',
                5 => 'success',
            ])
            ->hideOnIndex();

        yield AssociationField::new('albums')
            ->autocomplete()
            ->setFormTypeOption('by_reference', false);

        $tagsField = AssociationField::new('tags')
            ->autocomplete()
            ->setFormTypeOption('by_reference', false);
        if ($isNew) {
            $tagsField->setHelp('Will be auto-generated by AI, but you can change them');
        }
        yield $tagsField;

        yield IntegerField::new('viewCount')
            ->hideOnForm();

        yield DateTimeField::new('createdAt')
            ->setLabel('Date Taken')
            ->setFormTypeOption('disabled', true)
            ->setHelp('Auto-extracted from EXIF data')
            ->hideOnIndex();

        yield DateTimeField::new('uploadedAt')
            ->hideOnForm();

        // EXIF fields - always read-only
        yield TextField::new('copyright')
            ->setFormTypeOption('disabled', true)
            ->setHelp('Auto-extracted from EXIF data')
            ->hideOnIndex();

        yield TextField::new('device')
            ->setLabel('Camera/Device')
            ->setFormTypeOption('disabled', true)
            ->setHelp('Auto-extracted from EXIF data')
            ->hideOnIndex();

        yield TextField::new('location')
            ->setFormTypeOption('disabled', true)
            ->setHelp('Auto-extracted from EXIF data')
            ->hideOnIndex();

        yield NumberField::new('latitude')
            ->setNumDecimals(8)
            ->setFormTypeOption('disabled', true)
            ->setHelp('Auto-extracted from EXIF data')
            ->hideOnIndex();

        yield NumberField::new('longitude')
            ->setNumDecimals(8)
            ->setFormTypeOption('disabled', true)
            ->setHelp('Auto-extracted from EXIF data')
            ->hideOnIndex();

        yield NumberField::new('aperture')
            ->setNumDecimals(1)
            ->setLabel('Aperture (f-stop)')
            ->setFormTypeOption('disabled', true)
            ->setHelp('Auto-extracted from EXIF data')
            ->hideOnIndex();

        yield NumberField::new('focalLength')
            ->setNumDecimals(1)
            ->setLabel('Focal Length (mm)')
            ->setFormTypeOption('disabled', true)
            ->setHelp('Auto-extracted from EXIF data')
            ->hideOnIndex();

        yield TextField::new('exposureTime')
            ->setLabel('Shutter Speed')
            ->setFormTypeOption('disabled', true)
            ->setHelp('Auto-extracted from EXIF data')
            ->hideOnIndex();

        yield IntegerField::new('iso')
            ->setLabel('ISO')
            ->setFormTypeOption('disabled', true)
            ->setHelp('Auto-extracted from EXIF data')
            ->hideOnIndex();

        yield BooleanField::new('flash')
            ->setLabel('Flash Used')
            ->setFormTypeOption('disabled', true)
            ->setHelp('Auto-extracted from EXIF data')
            ->hideOnIndex();


    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        if (!$entityInstance instanceof Photo) {
            parent::persistEntity($entityManager, $entityInstance);
            return;
        }

        // Set the current user
        $entityInstance->setUser($this->getUser());

        // Process uploaded file
        if ($entityInstance->getFilename()) {
            $uploadDir = $this->getParameter('kernel.project_dir') . '/public/uploads/photos/';
            $filePath = $uploadDir . $entityInstance->getFilename();

            if (file_exists($filePath)) {
                // 1. Generate multiple image sizes
                $generatedSizes = $this->imageResizer->generateAllSizes($filePath, $uploadDir);

                // Store the generated filenames
                if (isset($generatedSizes[ImageResizer::SIZE_THUMBNAIL])) {
                    $entityInstance->setFilenameThumbnail($generatedSizes[ImageResizer::SIZE_THUMBNAIL]);
                }
                if (isset($generatedSizes[ImageResizer::SIZE_TABLET])) {
                    $entityInstance->setFilenameTablet($generatedSizes[ImageResizer::SIZE_TABLET]);
                }
                if (isset($generatedSizes[ImageResizer::SIZE_DESKTOP])) {
                    $entityInstance->setFilenameDesktop($generatedSizes[ImageResizer::SIZE_DESKTOP]);
                }

                // 2. Extract EXIF data
                $exifData = $this->exifExtractor->extractExifData($filePath);
                $this->applyExifData($entityInstance, $exifData);

                // 3. Analyze image with AI for name, description, and tags
                $aiProvider = $_ENV['AI_PROVIDER'] ?? 'openai';

                $aiData = match($aiProvider) {
                    'openai' => $this->aiImageAnalyzer->analyzeImageWithOpenAI($entityInstance->getFilename()),
                    'google' => $this->aiImageAnalyzer->analyzeImageWithGoogleVision($entityInstance->getFilename()),
                    default => $this->aiImageAnalyzer->analyzeImage($entityInstance->getFilename()),
                };

                // Apply AI-generated data only if fields are empty
                if (empty($entityInstance->getName()) && !empty($aiData['name'])) {
                    $entityInstance->setName($aiData['name']);
                }

                if (empty($entityInstance->getDescription()) && !empty($aiData['description'])) {
                    $entityInstance->setDescription($aiData['description']);
                }

                // Process AI-generated tags
                if (!empty($aiData['tags'])) {
                    $this->processTags($entityInstance, $aiData['tags'], $entityManager);
                }
            }
        }

        parent::persistEntity($entityManager, $entityInstance);
    }

    public function updateEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        if (!$entityInstance instanceof Photo) {
            parent::updateEntity($entityManager, $entityInstance);
            return;
        }

        // Check if a new file was uploaded during edit
        $uploadDir = $this->getParameter('kernel.project_dir') . '/public/uploads/photos/';
        $filePath = $uploadDir . $entityInstance->getFilename();

        if (file_exists($filePath)) {
            $fileModTime = filemtime($filePath);
            $uploadTime = $entityInstance->getUploadedAt()?->getTimestamp();

            // If file was modified after upload time, it's a new upload
            if ($uploadTime && $fileModTime > $uploadTime) {
                // Delete old resized versions
                $oldFilenames = [
                    $entityInstance->getFilenameThumbnail(),
                    $entityInstance->getFilenameTablet(),
                    $entityInstance->getFilenameDesktop(),
                ];
                $this->imageResizer->deleteAllSizes($uploadDir, $oldFilenames);

                // Generate new sizes
                $generatedSizes = $this->imageResizer->generateAllSizes($filePath, $uploadDir);

                if (isset($generatedSizes[ImageResizer::SIZE_THUMBNAIL])) {
                    $entityInstance->setFilenameThumbnail($generatedSizes[ImageResizer::SIZE_THUMBNAIL]);
                }
                if (isset($generatedSizes[ImageResizer::SIZE_TABLET])) {
                    $entityInstance->setFilenameTablet($generatedSizes[ImageResizer::SIZE_TABLET]);
                }
                if (isset($generatedSizes[ImageResizer::SIZE_DESKTOP])) {
                    $entityInstance->setFilenameDesktop($generatedSizes[ImageResizer::SIZE_DESKTOP]);
                }

                // Re-extract EXIF data
                $exifData = $this->exifExtractor->extractExifData($filePath);
                $this->applyExifData($entityInstance, $exifData);

                // Re-analyze with AI
                $aiProvider = $_ENV['AI_PROVIDER'] ?? 'openai';

                $aiData = match($aiProvider) {
                    'openai' => $this->aiImageAnalyzer->analyzeImageWithOpenAI($entityInstance->getFilename()),
                    'google' => $this->aiImageAnalyzer->analyzeImageWithGoogleVision($entityInstance->getFilename()),
                    default => $this->aiImageAnalyzer->analyzeImage($entityInstance->getFilename()),
                };

                // Update tags with AI suggestions (merge with existing)
                if (!empty($aiData['tags'])) {
                    $this->processTags($entityInstance, $aiData['tags'], $entityManager);
                }
            }
        }

        parent::updateEntity($entityManager, $entityInstance);
    }

    public function deleteEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        if ($entityInstance instanceof Photo) {
            // Delete all image files when deleting photo
            $uploadDir = $this->getParameter('kernel.project_dir') . '/public/uploads/photos/';
            $filenames = [
                $entityInstance->getFilename(),
                $entityInstance->getFilenameThumbnail(),
                $entityInstance->getFilenameTablet(),
                $entityInstance->getFilenameDesktop(),
            ];
            $this->imageResizer->deleteAllSizes($uploadDir, $filenames);
        }

        parent::deleteEntity($entityManager, $entityInstance);
    }

    private function applyExifData(Photo $photo, array $exifData): void
    {
        if ($exifData['device']) {
            $photo->setDevice($exifData['device']);
        }
        if ($exifData['copyright']) {
            $photo->setCopyright($exifData['copyright']);
        }
        if ($exifData['latitude']) {
            $photo->setLatitude($exifData['latitude']);
        }
        if ($exifData['longitude']) {
            $photo->setLongitude($exifData['longitude']);
        }
        if ($exifData['aperture']) {
            $photo->setAperture($exifData['aperture']);
        }
        if ($exifData['focalLength']) {
            $photo->setFocalLength($exifData['focalLength']);
        }
        if ($exifData['exposureTime']) {
            $photo->setExposureTime($exifData['exposureTime']);
        }
        if ($exifData['iso']) {
            $photo->setIso($exifData['iso']);
        }
        $photo->setFlash($exifData['flash']);

        if ($exifData['createdAt']) {
            $photo->setCreatedAt($exifData['createdAt']);
        }
    }

    private function processTags(Photo $photo, array $tagNames, EntityManagerInterface $entityManager): void
    {
        foreach ($tagNames as $tagName) {
            $tagName = trim($tagName);
            if (empty($tagName)) {
                continue;
            }

            // Find or create tag
            $tag = $this->tagRepository->findOneBy(['name' => $tagName]);
            if (!$tag) {
                $tag = new Tag();
                $tag->setName($tagName);
                $entityManager->persist($tag);
            }

            // Add tag to photo if not already present
            if (!$photo->getTags()->contains($tag)) {
                $photo->addTag($tag);
            }
        }
    }

    public function analyzeWithAi(AdminContext $context, EntityManagerInterface $entityManager, AdminUrlGenerator $adminUrlGenerator): RedirectResponse
    {
        /** @var Photo $photo */
        $photo = $context->getEntity()->getInstance();

        if (!$photo->getFilename()) {
            $this->addFlash('error', 'No image file found for AI analysis.');
            return $this->redirect($adminUrlGenerator
                ->setAction(Action::EDIT)
                ->setEntityId($photo->getId())
                ->generateUrl());
        }

        $uploadDir = $this->getParameter('kernel.project_dir') . '/public/uploads/photos/';
        $filePath = $uploadDir . $photo->getFilename();

        if (!file_exists($filePath)) {
            $this->addFlash('error', 'Image file not found on disk.');
            return $this->redirect($adminUrlGenerator
                ->setAction(Action::EDIT)
                ->setEntityId($photo->getId())
                ->generateUrl());
        }

        try {
            // Analyze image with AI
            $aiProvider = $_ENV['AI_PROVIDER'] ?? 'openai';

            $aiData = match($aiProvider) {
                'openai' => $this->aiImageAnalyzer->analyzeImageWithOpenAI($photo->getFilename()),
                'google' => $this->aiImageAnalyzer->analyzeImageWithGoogleVision($photo->getFilename()),
                default => $this->aiImageAnalyzer->analyzeImage($photo->getFilename()),
            };

            // Force update name and description (overwrite existing)
            if (!empty($aiData['name'])) {
                $photo->setName($aiData['name']);
            }

            if (!empty($aiData['description'])) {
                $photo->setDescription($aiData['description']);
            }

            // Process AI-generated tags (merge with existing)
            if (!empty($aiData['tags'])) {
                $this->processTags($photo, $aiData['tags'], $entityManager);
            }

            $entityManager->flush();

            $this->addFlash('success', 'Photo analyzed successfully with AI!');
        } catch (\Exception $e) {
            $this->addFlash('error', 'AI analysis failed: ' . $e->getMessage());
        }

        return $this->redirect($adminUrlGenerator
            ->setAction(Action::EDIT)
            ->setEntityId($photo->getId())
            ->generateUrl());
    }
}
